set read only at first slave startup and add read pool on haproxy

diff --git a/mysql-orchestrator-db/cloud-config.yml b/mysql-orchestrator-db/cloud-config.yml
--- a/mysql-orchestrator-db/cloud-config.yml
+++ b/mysql-orchestrator-db/cloud-config.yml
@@ -202,6 +202,9 @@ write_files:
             register: _xtrabackup_binlog_info
           - name: set up replica
             block:
+              - name: set read only at runtime
+                shell: >
+                  mysql -uroot -p${mysql_root_password} -e "set global read_only=true"
               - name: get gtid position
                 shell: cat ${mysql_datadir}/xtrabackup_binlog_info | cut -f3
                 register: _gtid_position
@@ -267,6 +270,133 @@ write_files:
       - name: haproxy
         hosts: 127.0.0.1
         pre_tasks:
+          - name: install xinetd
+            package: name=xinetd
+          - name: add xinetd check
+            copy:
+              dest: /etc/xinetd.d/mysqlchk
+              content: |
+                # default: on
+                # description: checkwrite
+                service mysqlchk
+                {
+                        disable = no
+                        flags = REUSE
+                        socket_type = stream
+                        port = 9300
+                        wait = no
+                        user = root
+                        server = /usr/local/sbin/mysqlchk
+                        log_on_failure += USERID
+                        per_source = UNLIMITED
+                }
+          - name: add service
+            lineinfile:
+              path: /etc/service
+              ragexp: '^mysqlchk'
+              line: 'mysqlchk 9300/tcp # mysqlchk for slaves'
+          - name: add script mysqlchk
+            copy:
+              dest: /usr/local/sbin/mysqlchk
+              mode: 0550
+              content: |
+                #!/bin/bash
+                #
+                # This script checks if a mysql server is healthy running on localhost. It will
+                # return:
+                # "HTTP/1.x 200 OK\r" (if mysql is running smoothly)
+                # - OR -
+                # "HTTP/1.x 500 Internal Server Error\r" (else)
+                #
+                # The purpose of this script is make haproxy capable of monitoring mysql properly
+                #
+                SLAVE_LAG_LIMIT=5
+                MYSQL_HOST="localhost"
+                MYSQL_PORT="${mysql_port}"
+                MYSQL_USERNAME='${mysql_admin_name}'
+                MYSQL_PASSWORD='${mysql_admin_password}'
+                MYSQL_BIN='/usr/bin/mysql'
+                MYSQL_OPTS="-q -A --connect-timeout=10"
+                TMP_FILE="/dev/shm/mysqlchk.$$.out"
+                ERR_FILE="/dev/shm/mysqlchk.$$.err"
+                FORCE_FAIL="/dev/shm/proxyoff"
+
+                preflight_check()
+                {
+                    for I in "$TMP_FILE" "$ERR_FILE"; do
+                        if [ -f "$I" ]; then
+                            if [ ! -w $I ]; then
+                                echo -e "HTTP/1.1 503 Service Unavailable\r\n"
+                                echo -e "Content-Type: Content-Type: text/plain\r\n"
+                                echo -e "\r\n"
+                                echo -e "Cannot write to $I\r\n"
+                                echo -e "\r\n"
+                                exit 1
+                            fi
+                        fi
+                    done
+                }
+
+                return_ok()
+                {
+                    echo -e "HTTP/1.1 200 OK\r\n"
+                    echo -e "Content-Type: text/html\r\n"
+                    echo -e "Content-Length: 43\r\n"
+                    echo -e "\r\n"
+                    if [ $role == "master" ]; then
+                        echo -e "<html><body>MySQL master is running.</body></html>\r\n"
+                    elif [ $role == "slave" ]; then
+                        echo -e "<html><body>MySQL slave is running. (Slave lag: $SLAVE_LAG)</body></html>\r\n"
+                    else
+                        echo -e "<html><body>MySQL is running.</body></html>\r\n"
+                    fi
+                    echo -e "\r\n"
+                  #  rm $ERR_FILE $TMP_FILE
+                    exit 0
+                }
+                return_fail()
+                {
+                    echo -e "HTTP/1.1 503 Service Unavailable\r\n"
+                    echo -e "Content-Type: text/html\r\n"
+                    echo -e "Content-Length: 42\r\n"
+                    echo -e "\r\n"
+                    echo -e "<html><body>MySQL is *down*.</body></html>\r\n"
+                    echo -e "\r\n"
+                    exit 1
+                }
+
+                preflight_check
+
+                if [ -f "$FORCE_FAIL" ]; then
+                        echo "$FORCE_FAIL found" > $ERR_FILE
+                        return_fail
+                fi
+
+                CMDLINE="$MYSQL_BIN $MYSQL_OPTS --host=$MYSQL_HOST --port=$MYSQL_PORT --user=$MYSQL_USERNAME --password=$MYSQL_PASSWORD -e"
+                SLAVE_IO=$(${CMDLINE} 'SHOW SLAVE STATUS' --vertical 2>/dev/null | grep Slave_IO_Running |  tail -1 | awk {'print $2'})
+                SLAVE_SQL=$(${CMDLINE} 'SHOW SLAVE STATUS' --vertical 2>/dev/null | grep Slave_SQL_Running | head -1 | awk {'print $2'})
+
+                if [[ "${SLAVE_IO}" == "Yes" ]] && [[ "${SLAVE_SQL}" == "Yes" ]]; then
+                    role='slave'
+                    SLAVE_LAG=$(${CMDLINE} 'SHOW SLAVE STATUS' --vertical 2>/dev/null | grep Seconds_Behind_Master | tail -1 | awk {'print $2'})
+                    if [[ $SLAVE_LAG = 0 ]]; then
+                        return_ok
+                    elif [[ $SLAVE_LAG < $SLAVE_LAG_LIMIT ]] ; then
+                        return_ok
+                    fi
+                else
+                    MASTER_SLAVE_HOSTS=$($CMDLINE 'SHOW SLAVE HOSTS' 2>/dev/null | wc -l)
+                    if [ $MASTER_SLAVE_HOSTS -gt 1 ]; then
+                        role='master'
+                        READ_ONLY=$($CMDLINE 'SHOW GLOBAL VARIABLES LIKE "read_only"' --vertical 2>/dev/null | tail -1 | awk {'print $2'})
+                        [[ "${READ_ONLY}" == "OFF" ]] && return_ok
+                    fi
+                fi
+
+                return_fail
+
+          - name: reload xinetd conf
+            service: name=xinetd state=reloaded
           - name: create consul template folder
             file:
               path: /opt/consul-template/templates
@@ -276,7 +406,7 @@ write_files:
               content: |
                 {% raw %}
                 listen write-pool
-                    bind *:3307
+                    bind *:${mysql_master_port}
                     mode tcp
                     server {{key "mysql/master/${orchestrator_cluster_name}/hostname"}} {{key "mysql/master/${orchestrator_cluster_name}/ipv4"}}:{{key "mysql/master/${orchestrator_cluster_name}/port"}} check port {{key "mysql/master/${orchestrator_cluster_name}/port"}}
                 {% endraw %}
@@ -285,6 +415,19 @@ write_files:
           - role: entercloudsuite.haproxy
             haproxy_user: ${mysql_admin_name}
             haproxy_pass: ${mysql_admin_password}
+            haproxy_conf: |
+              resolvers dns-consul
+                  nameserver dns consul.service.${consul_datacenter}.consul:53
+                  accepted_payload_size 8192
+                  hold valid 1s
+
+              listen slaves
+                  bind *:${mysql_slave_port}
+                  mode tcp
+                  option tcp-check
+                  tcp-check expect string is\ running.
+                  balance leastconn
+                  server-template swarm-worker 0-99 ${name}.service.automium.consul:${mysql_port} check port 9300 resolvers dns-consul
           - role: entercloudsuite.consul-template
             consul_template_use_systemd: true
             consul_template_consul_server: ${consul}
